# Generated by Django 4.0 on 2022-03-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_categorysubscribers_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_cat_en_us',
            field=models.CharField(max_length=62, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_cat_ru',
            field=models.CharField(max_length=62, null=True, unique=True, verbose_name='Название категории'),
        ),
    ]
