# Generated by Django 4.0 on 2022-03-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_categorysubscribers_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=512, verbose_name='Адрес'),
        ),
    ]
