# Generated by Django 4.0 on 2021-12-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_userrating_delete_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
