# Generated by Django 4.0 on 2022-03-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_name_cat_en_us_category_name_cat_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(max_length=255, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок'),
        ),
    ]
