openapi: 3.0.2
info:
 title: 'News portal'
 version: '1.0'
tags:
  - name: News
    description: All about news
  - name: Articles
    description: All about articles
paths:
 /api/v1/news/:
   get:
     tags:
       - News
     summary: Return all news
     operationId: listNews
     description: Method allows you to get all the news
     parameters: []
     responses:
       '200':
         content:
           application/json:
             schema:
               type: array
               items:
                 $ref: '#/components/schemas/posts'
         description: ''
       '404':
          description: 'Not found'

   post:
     tags:
       - News
     summary: Add news
     operationId: createNews
     description: Method allows you to create news
     requestBody:
       description: Create a news
       content:
          application/json:
            schema:
              $ref: '#/components/schemas/add_posts'
       required: true
     responses:
       '201':
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/posts'
         description: 'Success'
       '400':
         description: 'Bad request'
       '401':
         description: 'Unauthorized'
       '403':
         description: 'Forbidden'

 /api/v1/news/{id}/:
   get:
     tags:
       - News
     summary: Get an existing news
     description: Get an existing news by Id
     operationId: getNews
     parameters:
       - name: id
         in: path
         required: true
         schema:
            type: integer
            format: int64
     responses:
       '201':
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/posts'
         description: 'Success'
       '404':
         description: Not Found

   put:
     tags:
       - News
     summary: Update an existing news
     description: Update an existing news by Id
     operationId: updateNews
     parameters:
       - name: id
         in: path
         required: true
         schema:
            type: integer
            format: int64
     requestBody:
        description: Update an existent news
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add_posts'
        required: true
     responses:
       '201':
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/posts'
         description: 'Success'
       '400':
         description: 'Bad request'
       '404':
         description: Not Found

   delete:
     tags:
       - News
     summary: Delete a news
     description: Delete a news by ID
     operationId: deleteNews
     parameters:
       - name: id
         in: path
         required: true
         schema:
            type: integer
            format: int64
     responses:
       '204':
         description: 'Successful delete'
       '403':
         description: 'Forbidden'
       '404':
         description: Not Found

 /api/v1/articles/:
   get:
     tags:
       - Articles
     summary: Return all articles
     operationId: listArticles
     description: Method allows you to get all the articles
     parameters: []
     responses:
       '200':
         content:
           application/json:
             schema:
               type: array
               items:
                 $ref: '#/components/schemas/posts'
         description: ''
       '404':
          description: 'Not found'
   post:
     tags:
       - Articles
     summary: Add articles
     operationId: createArticles
     description: Method allows you to create articles
     requestBody:
       description: Create a articles
       content:
          application/json:
            schema:
              $ref: '#/components/schemas/add_posts'
       required: true
     responses:
       '201':
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/posts'
         description: 'Success'
       '400':
         description: 'Bad request'
       '401':
         description: 'Unauthorized'
       '403':
         description: 'Forbidden'

 /api/v1/articles/{id}/:
   get:
     tags:
       - Articles
     summary: Get an existing articles
     description: Get an existing articles by Id
     operationId: getArticles
     parameters:
       - name: id
         in: path
         required: true
         schema:
            type: integer
            format: int64
     responses:
       '201':
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/posts'
         description: 'Success'
       '404':
         description: Not Found

   put:
     tags:
       - Articles
     summary: Update an existing articles
     description: Update an existing articles by Id
     operationId: updateArticles
     parameters:
       - name: id
         in: path
         required: true
         schema:
            type: integer
            format: int64
     requestBody:
        description: Update an existent articles
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/add_posts'
        required: true
     responses:
       '201':
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/posts'
         description: 'Success'
       '400':
         description: 'Bad request'
       '404':
         description: Not Found

   delete:
     tags:
       - Articles
     summary: Delete a articles
     description: Delete a articles by ID
     operationId: deleteArticles
     parameters:
       - name: id
         in: path
         required: true
         schema:
            type: integer
            format: int64
     responses:
       '204':
         description: 'Successful delete'
       '403':
         description: 'Forbidden'
       '404':
         description: Not Found

components:
 schemas:
   posts:
     type: object
     properties:
       id:
         type: integer

         example: 10
       author:
         type: string
         maxLength: 64
         example: admin
       date_time:
         type: string
         example: '2021-12-26 11:51:57.846195'
       title:
         type: string
         example: Some title
       text:
         type: string
         example: Some text
       rating:
         type: integer
         example: 3
       url:
         type: string
         example: 'https://neftegaz.ru/news/Oborudovanie/713284-razrabotka-kazanskikh-uchenykh-kastorovyy-ingibitor-voshla-v-chislo-luchshikh-eko-novatsiy/'
     required:
     - name

   add_posts:
     type: object
     properties:
       id:
         type: integer
         readOnly: true
       title:
         type: string
         example: Some title
       text:
         type: string
         example: Some text
       url:
         type: string
         example: 'https://neftegaz.ru/news/Oborudovanie/713284-razrabotka-kazanskikh-uchenykh-kastorovyy-ingibitor-voshla-v-chislo-luchshikh-eko-novatsiy/'